%% EventCatalog Mermaid Diagram
%% Resource: services/CoreEventInjector (v0.0.1)
%% Generated: 2026-05-24T10:44:55.001Z

flowchart LR

    %% Style definitions
    classDef services fill:#ec4899,stroke:#be185d,color:#fff
    classDef data fill:#3b82f6,stroke:#1d4ed8,color:#fff
    classDef events fill:#f97316,stroke:#c2410c,color:#fff

    %% Nodes
    CoreEventInjector_0_0_1[["Core Event Injector (0.0.1)"]]:::services
    CoreEventStore_0_0_1[("Core Event Store")]:::data
    TransactionImportCompleted_0_0_1>"Transaction Import Completed (0.0.1)"]:::events
    TransactionImportFailed_0_0_1>"Transaction Import Failed (0.0.1)"]:::events

    %% Edges
    CoreEventInjector_0_0_1 -->|"writes to   (postgres)"| CoreEventStore_0_0_1
    CoreEventInjector_0_0_1 -->|"publishes  event"| TransactionImportCompleted_0_0_1
    CoreEventInjector_0_0_1 -->|"publishes  event"| TransactionImportFailed_0_0_1